### ISSUE TITLE
Clarity about which browsers this app runs on

### ISSUE THREAD

**Issue by sofer** [CYPIAPT-LNDSE/Face-It#175]
Could you confirm which browsers and from which versions this runs?

**Comment by sofer** [comment]
(I notice that there is a change to the README wording in an open PR) 👍

**Comment by daymos** [comment]
The app was meant as a mobile app, so we didn't really bothered with browser support beyond what is needed for android and possibly ios. 
There is a version deployed on gh-pages because mark requested it for purposes of showing it around at presentation and talks. But its only guaranteed to work on a late version of chrome as far as I know. 
Personally I don't think the work required to make it cross compatible is worth given that it wont be a webapp ( at least that was the original plan )

**Comment by daymos** [comment]
in terms of android we are compatible at least back to 4.4.

**Comment by daymos** [comment]
<img width="767" alt="schermata 2016-11-03 alle 17 52 21" src="https://cloud.githubusercontent.com/assets/5450558/19978299/5a467864-a1ee-11e6-8c29-f05d542b85a9.png">

**Comment by sofer** [comment]
@daymos great answers. See also #177

**Comment by helau64** [comment]
Yeah, to be totally clear – once my pull request is merged, it'll work on Chrome and Firefox; we're meeting today to work on getting it fixed in Safari
