### ISSUE TITLE
upcoming sprint

### ISSUE THREAD

**Issue by daymos** [CYPIAPT-LNDSE/Face-It#70]
hi simon, ,should we slowly start to talk about the next sprint?

**Comment by SimonJStewart** [comment]
Yes seems like a good idea. 

I have groups of users who'll be able to give feedback at the end of this sprint to feed into the next one, so if there are specific things in development where feedback would be valuable let me know .

You also mentioned that gathering faces with appropriate confidence ratings was problematic - i can work on sourcing these if it will free up your time. 

The outline of the two week sprint on the wiki sounds good to me - although I'd be interested in getting some effort estimates.

In particular I'm wondering if deprioritising the characterisation would free up time to create one of the alternative types of levels we've discussed as later release things: 

non-binary choice, 
guess the confidence level, 
take a photo of you looking happy, 
take a photo of your friend looking happy

As I'm thinking this will show more depth in the product when we start looking for funding of later releases, and that the product is viable without the characterisation.

**Comment by daymos** [comment]
Hi Simon, I would postpone effort estimate for the whole project to a later stage, because in order to do that we would need a lot more details on every single feature we will want to introduce. 

Our agreement with anna freud is for 2 further sprints, 2 weeks in length each. Based on what I know now, I can tell you about the the first one, which starts today.

So my most realistic forecast, is that we will spend most of the next 2 weeks making the existing features of the prototype robust, and ready for actual release. We will also implement the features we just stubbed for the presentation, namely the detailed result page with the graphs.
On top of that, we could  add the non binary choice feature. 

The other features that you mention, will have to be evaluated  for the second sprint in 2 weeks.  This step is required, and non avoidable, since the prototyping week we had, was not meant to result in a viable product. 

If you want to work on sourcing pictures that would be of great help. So Im all for it. However might be worth thinking about  a different approach for the long run. 
I see 2 possibilities: first option  we keep sourcing the pictures for the game ourselves. This require a fair amount of work on our part that need to be kept up in time. We could develop a tool to make it faster. 
Second option, we let users upload pictures, and use those for the game. This can be tricky for technical reasons ( and legal too I imagine ), but we will not run the risk of having people finishing the game in a few days and loosing interests. 
Keeping in mind that one kid reached 1400 level on candy crush, I see this as a priority over the rest for the success of the project.

**Comment by SimonJStewart** [comment]
That would be great for this sprint - sounds like it will provide enough for me to show something working to interested stakeholders and get them to understand the potential of the product.

My thinking on the pictures was that we would have some pre-loaded pictures and (eventually) have later levels which involve users taking their own pictures of themselves/friends/family with different expressions. I'm keen to do this as it adds a social dimension to the game as well as variety. However, as these would be new pictures it would mean making calls to the API from the app rather than the current method of analysing them and loading in the results. So from a technical point of view I would like the app to have the capability of calling the API on photos from a device camera / saved on the device. But whether this can be achieved in the time we've got for MVP I'm not sure, I was assuming not which is why I had it in later releases on the roadmap (and it's not essential for MVP). If it could be done it would be great though.

In terms of pictures for pre-loading and considerations for development of a tool: 

For the early levels of the game we were looking for faces that are very clearly showing a single emotion (e.g. 90-100% confidence). As the game progresses we will want to make things more challenging so we'll be looking for lower confidence ratings (and eventually we may get to the point of "which two emotions does this face look most like it is expressing?")

So it sounds like we need something to call the API and record the results and then sort images by highest confidence rating and group them by emotion. 

Does that sound right?

This is something I can do manually for now if there is a repository somewhere I can put them in for you?

**Comment by daymos** [comment]
cool, then we agree on the scoping of the current sprint. 
This is the repo, if you know how to push stuff up feel free to do it. If you need an intro on that you can come by here and I'll show you. Otherwise save then on your machine and send them to me with www.wetransfer.com/
Where are you planning to get the licensed images?

**Comment by daymos** [comment]
Btw shall we have a chat over the phone this week?

**Comment by SimonJStewart** [comment]
Yes happy to whenever required.

Images i was planning to find by just searching for anything licensed for commercial use with modification - is this appropriate?

**Comment by helau64** [comment]
Yeah, that's fine, though if you find yourself running into difficulties finding images, feel free to open the search to any of the google image license filters – given that the app will be being released for free, I think it counts as noncommercial use
